# Paths
all_video_names: list/all.video
video_path: /data/VOL4/sshalini/data/speech-kitchen.org/sdalmia/11775_videos/video
downsampled_videos: /data/VOL4/rrnigam/lsma/11775-hw1/hw2_code/downsampled_videos
surf_features: /data/VOL4/rrnigam/lsma/11775-hw1/hw2_code/surf
cnn_features: /data/VOL4/rrnigam/lsma/11775-hw1/hw2_code/cnn

# downsampling
downsampling_frame_len: 60
downsampling_frame_rate: 15
keyframe_interval: 5

# surf
hessian_threshold: 400
kmeans_cluster_num: 256